In [15]:
import torch
import torch.nn as nn 
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8
batch_size = 4

cpu


In [17]:
with open('Frankenstein.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
print(chars)
vocab_size = len(chars)

['\n', ' ', '!', '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'æ', 'è', 'é', 'ê', 'ô', '—', '‘', '’', '“', '”', '\ufeff']


In [18]:
string_to_int = { ch:i for i,ch in enumerate(chars) }
int_to_string = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([83, 26, 64, 47, 60, 57, 51, 60, 65, 66, 51, 55, 60, 19,  0,  0, 61, 64,
         5,  1, 66, 54, 51,  1, 33, 61, 50, 51, 64, 60,  1, 36, 64, 61, 59, 51,
        66, 54, 51, 67, 65,  0,  0, 48, 71,  1, 33, 47, 64, 71,  1, 42, 61, 58,
        58, 65, 66, 61, 60, 51, 49, 64, 47, 52, 66,  1,  3, 27, 61, 50, 69, 55,
        60,  4,  1, 38, 54, 51, 58, 58, 51, 71,  0,  0,  0,  1, 23, 35, 34, 39,
        25, 34, 39, 38,  0,  0,  1, 32, 51, 66])


In [19]:
# Define percentage
n = int(0.8*len(data))
# 80 % split for training 
train_data = data[:n]
# 20 % split for validating
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    x =  torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x,y = x.to(device), y.to(device)
    return x,y
    
x,y = get_batch('train')
print('inputs:')

print(x)
print('targets:')
print(y)
# z,a = get_batch('none')
# print(z)
# print(a)

tensor([ 33184, 223605, 304301, 161720])
inputs:
tensor([[65,  1, 66, 51, 60,  0, 59, 61],
        [50, 51, 58, 55, 68, 51, 64, 51],
        [ 5,  1, 69, 55, 66, 54,  1, 66],
        [ 1, 61, 52,  1, 23, 54, 47, 59]])
targets:
tensor([[ 1, 66, 51, 60,  0, 59, 61, 60],
        [51, 58, 55, 68, 51, 64, 51, 50],
        [ 1, 69, 55, 66, 54,  1, 66, 64],
        [61, 52,  1, 23, 54, 47, 59, 61]])


In [20]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print('when input is', context, 'target is', target)

when input is tensor([83]) target is tensor(26)
when input is tensor([83, 26]) target is tensor(64)
when input is tensor([83, 26, 64]) target is tensor(47)
when input is tensor([83, 26, 64, 47]) target is tensor(60)
when input is tensor([83, 26, 64, 47, 60]) target is tensor(57)
when input is tensor([83, 26, 64, 47, 60, 57]) target is tensor(51)
when input is tensor([83, 26, 64, 47, 60, 57, 51]) target is tensor(60)
when input is tensor([83, 26, 64, 47, 60, 57, 51, 60]) target is tensor(65)


In [16]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding 

SyntaxError: expected ':' (2983650371.py, line 1)