In [28]:
import torch
import numpy as np 
import time
import torch.nn as nn
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [5]:
start_time = time.time()
# Matrix operations here
zeros = torch.zeros(1,1,2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00177717


In [8]:
%%time
torch_rand1 = torch.rand(100,100,100, 100).to(device)
torch_rand2 = torch.rand(100,100,100, 100).to(device)
np_rand1 = torch.rand(100,100,100, 100)
np_rand2 = torch.rand(100,100,100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.17773962
0.23084831
CPU times: user 3.32 s, sys: 695 ms, total: 4.01 s
Wall time: 3.58 s


In [11]:
%%time
# define probability tensor
probabilities = torch.tensor([0.25,0.5,0.25])
#  25/50/25 odds of returning index of probability tensor
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([2, 0, 2, 1, 1, 1, 1, 2, 1, 1])
CPU times: user 5.22 ms, sys: 0 ns, total: 5.22 ms
Wall time: 5.25 ms


In [15]:
out = torch.tril(torch.ones(5,6))
out

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.]])

In [14]:
out = torch.triu(torch.ones(6,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])

In [16]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [17]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [19]:
input = torch.zeros(2,3,4)
out = input.transpose(0,1)
out.shape

torch.Size([3, 2, 4])

In [20]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# Stack the Tensors along a new dimension
stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=True)
print(linear(sample))

tensor([-8.7709, -0.2062, -5.4801], grad_fn=<ViewBackward0>)


In [27]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [32]:
# init an embedding layer 
vocab_size = 1000 
embedding_dim = 100 
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1,5,3,2])

# Apply the embedding layer 
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4,100), where 4 is the number of inputs 
# and 100 is the dimensionality of the embedding vectors 
print(embedded_output.shape)

torch.Size([4, 100])


In [35]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# multipling matrices
print(a @ b)
# or torch.matmul(a,b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [39]:
int_64 = torch.randint(1,(3,2)).float()

float_32 = torch.rand(2,3)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [42]:
import random
num_dims = random.randint(1, 5)  # You can adjust the range as needed

# Generate random sizes for each dimension
sizes = [random.randint(1, 10) for _ in range(num_dims)]

# Create a random tensor with random values
random_tensor = torch.randn(*sizes)

print("Random Tensor:")
print(random_tensor)
print("Tensor Shape:", random_tensor.shape)

Random Tensor:
tensor([[[[ 1.5253,  0.3347, -0.4790,  0.6741, -0.0302, -0.1581,  1.0707],
          [ 1.3938,  0.0888, -0.6143,  0.7503,  1.7704,  0.1085, -1.5084],
          [-0.4410,  2.0123,  0.0475,  0.8538,  1.6149, -2.2552,  0.2094],
          [-1.0271, -1.1164, -0.3252, -0.1518,  0.9868,  0.2050,  1.2111],
          [-1.3865, -0.4771, -1.3248, -0.9415,  0.2968, -1.2819,  1.1336],
          [ 1.2445, -0.8480,  1.4416,  0.8120, -0.9317, -0.6176, -0.0375],
          [ 1.1157, -0.0311, -0.2508, -0.5020,  0.6043, -0.3415, -0.3869],
          [ 0.2254, -0.6482, -0.2086,  0.8989, -0.7834, -0.3399,  0.8202],
          [-0.3471,  0.2749,  0.8002,  0.5173, -1.9704,  0.1889, -1.5428]],

         [[-0.8008, -0.8505,  1.0115,  0.1395,  0.8801, -0.6566, -1.9394],
          [-0.9435,  0.5501,  0.5370,  0.4623,  0.9344, -0.1056,  2.4480],
          [ 0.7905,  0.3158,  1.9884,  0.0083,  0.2907, -0.7016, -1.7093],
          [ 0.3695,  1.3219,  1.5941,  0.3369,  0.7779,  1.8537, -1.1847],
        