In [9]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-46,  88,  -2, -43,   3,  37])

In [3]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(1,2,3)
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [6]:
input = torch.empty(2,3)
input

tensor([[ 9.9840e+09,  3.0750e-41,  8.5422e+08],
        [ 3.0750e-41, -2.5263e-08,  4.5846e-41]])

In [7]:
arange = torch.arange(6)
arange

tensor([0, 1, 2, 3, 4, 5])

In [12]:
linspace = torch.linspace(3,10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [13]:
logspace = torch.logspace(-10,10,5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [14]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[    140522810260992,     140522810260992, 4121974776714323043],
        [2464094860490465891, 8385534776637005868, 7287422581096149113]])